# Generated by gemini and me
import numpy as np
from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector
import matplotlib.pyplot as plt

def append_qft(circuit, qubits):
    """在指定的 qubits 上添加 1D QFT 电路"""
    n = len(qubits)
    # 1. 旋转部分
    for i in range(n):
        circuit.h(qubits[n-i-1])
        for j in range(n-i-1):
            theta = np.pi / (2**(n-i-j-1))
            circuit.cp(theta, qubits[j], qubits[n-i-1])
    # 2. 交换部分 (比特翻转恢复)
    for i in range(n // 2):
        circuit.swap(qubits[i], qubits[n-i-1])

def qft_2d_circuit_on_qc(qc, n_rows, n_cols):
    """
    创建 2D QFT 电路
    n_rows: 行量子比特数 (维度为 2^n_rows)
    n_cols: 列量子比特数 (维度为 2^n_cols)
    """
    total_qubits = n_rows + n_cols
    # qc = QuantumCircuit(total_qubits)
    
    row_qubits = list(range(n_rows))
    col_qubits = list(range(n_rows, total_qubits))
    
    # 步骤 1: 对行应用 QFT
    append_qft(qc, row_qubits)
    
    # 步骤 2: 对列应用 QFT
    append_qft(qc, col_qubits)
    

# --- 验证部分 ---
# n = 3  # 2个比特代表4行，2个比特代表4列，总共 4x4 的矩阵
# N = 2**n
row_n = 1
col_n = 2
row_N = 2**row_n
col_N = 2**col_n
# input_matrix = np.random.rand(row_N, col_N) + 1j*np.random.rand(row_N, col_N)
input_matrix = np.array([
                        [1,2,3,4],
                         [7,3,4,5]
                         ])

# 1. 经典归一化 2D IFFT (与 QFT 方向一致)
# 这里的归一化因子是 1/sqrt(N*N) = 1/N
classic_2d = np.fft.ifft2(input_matrix) * np.sqrt(row_N * col_N) 

# 2. 量子模拟
# 展平矩阵并归一化为态矢量
flat_vector = input_matrix.flatten()
input_state = flat_vector / np.linalg.norm(flat_vector)

qc = QuantumCircuit(row_n + col_n)
qc.initialize(input_state, range(row_n + col_n))
qft_2d_circuit_on_qc(qc, col_n, row_n) # 注意行列对应的量子比特

qc.draw('mpl', fold=-1)
plt.show()

quantum_result = Statevector.from_instruction(qc).data
# 将结果重新塑形为矩阵
quantum_matrix = quantum_result.reshape(row_N, col_N)

print("input")
print(input_matrix)
print("经典")
print(np.round(classic_2d/np.linalg.norm(classic_2d), 4))
print("量子")
print(np.round(quantum_matrix, 4))
print(f"验证是否一致: {np.allclose(classic_2d/np.linalg.norm(classic_2d), quantum_matrix, atol=1e-10)}")