# Generated by Gemini

import numpy as np
from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector
from qiskit import transpile
from qiskit_aer import AerSimulator


# 1. 定义一个简单的 2x2 图像 (4个像素)
image = np.array([0.5, 0.2, 0.8, 0.1])

# 2. 归一化像素值以获得概率幅度
norm = np.linalg.norm(image)
amplitudes = image / norm

# 3. 使用 Qiskit 的 initialize 方法制备状态
# 对于 4 个像素，需要 n = log2(4) = 2 个量子比特
qc = QuantumCircuit(2)
qc.initialize(amplitudes, [0, 1])

# 查看电路
print(qc.draw())

########################################################

# 1. 在末端添加测量
qc.measure_all()

# 2. 运行模拟器
simulator = AerSimulator()
compiled_circuit = transpile(qc, simulator)
shots = 10000
job = simulator.run(compiled_circuit, shots=shots)
result = job.result()
counts = result.get_counts()

# 3. 还原幅度
restored_amplitudes = np.zeros(4)
for bitstring, count in counts.items():
    idx = int(bitstring, 2)
    restored_amplitudes[idx] = np.sqrt(count / shots)

print("原始归一化幅度:", amplitudes)
print("还原后的幅度:", restored_amplitudes)